server.port=8761

spring.application.name=eureka-server-service-discovery

eureka.server.app.message=Hello Eureka Server from Config Server

# eureka server - unregistering eureka client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# disable error logs in console
logging.level.com.netflix.discovery.shared.transport.jersey3.EurekaJersey3ClientImpl=OFF
