server.port=8080

spring.application.name=eureka-client-api-gateway

api.gateway.app.message=Hello from API Gateway from Config Server

# eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# gateway routes
spring.cloud.gateway.server.webflux.routes[0].id=help-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://help-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/help/**

spring.cloud.gateway.server.webflux.routes[1].id=restclient-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://restclient-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/help/restclient/**

spring.cloud.gateway.server.webflux.routes[2].id=kafka-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://kafka-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/kafka/**

# auto discover locator of help, kafka, restclient ... service
# spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.gateway.enabled=true

# Actuator Info
info.app.name=API Gateway
info.app.description=Spring Cloud API Gateway
info.app.version=1.0.0

# eureka connected logs
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.eureka=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

# Gateway tracing logs
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route=TRACE
