server.port=8080

spring.application.name=eureka-client-api-gateway

api.gateway.app.message=Hello API Gateway from Config Server

# ==================================================================================================================================
# eureka client
# ==================================================================================================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==================================================================================================================================
# gateway routes [manual discovery]
# help-service
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[0].id=help-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://help-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/help/**
# ==================================================================================================================================
# help-service circuit breaker
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[0].filters[0]=CircuitBreaker=helpCircuitBreaker,forward:/fallback/help
# ==================================================================================================================================
# help-service redis rate limiter
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.replenishRate=1
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.burstCapacity=2
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.key-resolver=#{@ipKeyResolver}

# ==================================================================================================================================
# restclient-service
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[1].id=restclient-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://restclient-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/restclient/**
# ==================================================================================================================================
# restclient-service circuit breaker
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[1].filters[0]=CircuitBreaker=restclientCircuitBreaker,forward:/fallback/restclient
# ==================================================================================================================================
# restclient-service redis rate limiter
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[1].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.redis-rate-limiter.replenishRate=1
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.redis-rate-limiter.burstCapacity=2
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.key-resolver=#{@ipKeyResolver}

# ==================================================================================================================================
# kafka-service
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[2].id=kafka-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://kafka-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/kafka/**
# ==================================================================================================================================
# kafka-service circuit breaker
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[2].filters[0]=CircuitBreaker=kafkaCircuitBreaker,forward:/fallback/kafka
# ==================================================================================================================================
# kafka-service redis rate limiter
# ==================================================================================================================================
spring.cloud.gateway.server.webflux.routes[2].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.redis-rate-limiter.replenishRate=1
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.redis-rate-limiter.burstCapacity=2
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.key-resolver=#{@ipKeyResolver}

# ==================================================================================================================================
# gateway routes [auto discovery]
# ==================================================================================================================================
# auto discover locator of help, kafka, restclient ... service
#spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# ==================================================================================================================================
# Actuator
# ==================================================================================================================================
management.endpoints.web.exposure.include=health,info,gateway,metrics,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.gateway.enabled=true

# ==================================================================================================================================
# Actuator Info
# ==================================================================================================================================
info.app.name=API Gateway
info.app.description=Spring Cloud API Gateway
info.app.version=1.0.0

# ==================================================================================================================================
# eureka connected logs
# ==================================================================================================================================
logging.level.com.netflix.discovery=DEBUG
logging.level.com.netflix.eureka=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

# ==================================================================================================================================
# Gateway tracing logs
# ==================================================================================================================================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.cloud.gateway.route=TRACE
logging.level.reactor.netty.http.client=DEBUG

# ==================================================================================================================================
# circuit breaker
# help-service circuit breaker 
# ==================================================================================================================================
resilience4j.circuitbreaker.instances.helpCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.helpCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.helpCircuitBreaker.failure-rate-threshold=11
resilience4j.circuitbreaker.instances.helpCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.helpCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.helpCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true
# ==================================================================================================================================
# restClient-service circuit breaker 
# ==================================================================================================================================
resilience4j.circuitbreaker.instances.restclientCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.restclientCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.restclientCircuitBreaker.failure-rate-threshold=11
resilience4j.circuitbreaker.instances.restclientCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.restclientCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.restclientCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true
# ==================================================================================================================================
# kafka-service circuit breaker 
# ==================================================================================================================================
resilience4j.circuitbreaker.instances.kafkaCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.kafkaCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.kafkaCircuitBreaker.failure-rate-threshold=11
resilience4j.circuitbreaker.instances.kafkaCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.kafkaCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.kafkaCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true

# ==================================================================================================================================
# circuit breaker debug logs
# ==================================================================================================================================
logging.level.io.github.resilience4j.circuitbreaker=DEBUG

# ==================================================================================================================================
# Redis
# ==================================================================================================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==================================================================================================================================
# OAuth2 - Keycloak
# ==================================================================================================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/microservices
