server.port=8081
spring.application.name=help-service

app.message=Hello Help Service from Config Server

#spring.banner.location=classpath:banner.txt
#spring.main.banner-mode=console

server.tomcat.threads.max=200
spring.main.allow-bean-definition-overriding=true

# oracle database
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orcl

spring.datasource.username=system
spring.datasource.password=smile123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring.thymeleaf.cache=false
spring.main.show-banner=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.root=INFO
logging.level.com.org.help=DEBUG

rest.client.base.url=http://localhost:8081/api/help

# Kafka server
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Topic
spring.kafka.topic.name=help-topic
# Consumer
spring.kafka.consumer.group-id=help-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# JSON deserialization
spring.kafka.consumer.properties[spring.json.trusted.packages]=com.org.help

# registering eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Actuator Info
info.app.name=Help Service
info.app.description=Spring Boot Help Service
info.app.version=1.0.0

# ==================================================================================================================================
# OAuth2 - Keycloak
# ==================================================================================================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/microservices
