server.port=8082
spring.application.name=restclient-service

restclient.app.message=Hello from Restclient Service Config Server

spring.boot.base.url=http://localhost:8081/api/help

spring.thymeleaf.cache=false
spring.main.show-banner=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG
